{
  "config_name": "X17U_borndead_Master_OVX10500U_HP9_50M_200M",
  "author": "borndead (feat. itzdfplayer, amitkattal & GeorgeKiarie)",
  "device": "Xiaomi 17 Ultra (nezha)",
  "version": "v1.0-50M-200M-Nezha",
  "camera_model": "Xiaomi 17 Ultra Master Leica Setup",
  "general": {
    "hdr_type": "hdr_plus_enhanced",
    "raw_format": "RAW16",
    "high_res_enabled": true,
    "shutter_speed_mode": "auto",
    "iso_mode": "auto",
    "exposure_compensation": "0",
    "dng_output": true,
    "focus_mode": "continuous"
  },
  "lenses": [
    {
      "id": 0,
      "name": "Main 1.0x (OmniVision OVX10500U 1-inch)",
      "sensor": "OmniVision OVX10500U 50MP 1-inch LOFIC DCG",
      "camera_id": 0,
      "high_res": true,
      "output_resolution": "8192x6144",
      "op_mode": "0xF000",
      "raw_format": "RAW16",
      "hdr_frames": 3,
      "black_level": [64.0, 64.0, 64.0, 64.0],
      "white_level": 1023,
      "cct_matrix": "nezha_ovx10500u_tuned",
      "noise_model": "ovx10500u_dcg_noise",
      "noise_reduction_strength": 0.40,
      "sharpness_strength": 1.20,
      "dcg_enabled": true
    },
    {
      "id": 1,
      "name": "Periscope 5.0x (Samsung HP9 200MP)",
      "sensor": "Samsung S5KHP9 200MP",
      "camera_id": 4,
      "high_res": true,
      "output_resolution": "16384x12288",
      "op_mode": "0xF000",
      "raw_format": "RAW16",
      "hdr_frames": 2,
      "black_level": [64.0, 64.0, 64.0, 64.0],
      "white_level": 1023,
      "cct_matrix": "nezha_hp9_tele",
      "noise_model": "hp9_tele_noise",
      "noise_reduction_strength": 0.45,
      "sharpness_strength": 1.25,
      "dcg_enabled": true
    },
    {
      "id": 2,
      "name": "Telephoto 3.0x",
      "sensor": "Samsung 50MP Tele",
      "camera_id": 2,
      "high_res": true,
      "output_resolution": "8192x6144",
      "op_mode": "0xF000",
      "raw_format": "RAW16",
      "hdr_frames": 3,
      "black_level": [64.0, 64.0, 64.0, 64.0],
      "white_level": 1023,
      "cct_matrix": "nezha_tele3x",
      "noise_model": "tele3x_noise",
      "noise_reduction_strength": 0.45,
      "sharpness_strength": 1.15,
      "dcg_enabled": true
    },
    {
      "id": 3,
      "name": "Ultra-Wide 0.5x (Samsung JN5)",
      "sensor": "Samsung S5KJN5 50MP",
      "camera_id": 1,
      "high_res": true,
      "output_resolution": "8192x6144",
      "op_mode": "0xF000",
      "raw_format": "RAW16",
      "hdr_frames": 3,
      "black_level": [64.0, 64.0, 64.0, 64.0],
      "white_level": 1023,
      "cct_matrix": "nezha_jn5",
      "noise_model": "jn5_noise",
      "noise_reduction_strength": 0.50,
      "sharpness_strength": 1.10,
      "dcg_enabled": true
    }
  ]
}
