{
  "config_name": "Mi14U_borndead_Universal_Leica_LYT900_Quad50M",
  "author": "borndead (feat. itzdfplayer, amitkattal & GeorgeKiarie)",
  "device": "Xiaomi 14 Ultra (aurora)",
  "version": "v1.0-Quad50M-RAW16",
  "camera_model": "Xiaomi 14 Ultra Leica Quad-50M",
  "general": {
    "hdr_type": "hdr_plus_enhanced",
    "raw_format": "RAW16",
    "high_res_enabled": true,
    "shutter_speed_mode": "auto",
    "iso_mode": "auto",
    "exposure_compensation": "0",
    "dng_output": true,
    "focus_mode": "continuous",
    "variable_aperture_support": true
  },
  "lenses": [
    {
      "id": 0,
      "name": "Main 1.0x (Sony LYT-900 1-inch)",
      "sensor": "Sony LYT-900 50MP 1-inch Quad-Bayer",
      "camera_id": 0,
      "high_res": true,
      "output_resolution": "8192x6144",
      "op_mode": "0xF000",
      "raw_format": "RAW16",
      "hdr_frames": 3,
      "black_level": [64.0, 64.0, 64.0, 64.0],
      "white_level": 1023,
      "cct_matrix": "leica_authentic_lyt900",
      "noise_model": "lyt900_low_noise",
      "noise_reduction_strength": 0.40,
      "sharpness_strength": 1.15,
      "dcg_enabled": true,
      "physical_aperture_steps": ["1.63", "2.0", "2.8", "4.0"]
    },
    {
      "id": 1,
      "name": "Ultra-Wide 0.5x (Sony IMX858 12mm)",
      "sensor": "Sony IMX858 Quad-Bayer",
      "camera_id": 1,
      "high_res": true,
      "output_resolution": "8192x6144",
      "op_mode": "0xF000",
      "raw_format": "RAW16",
      "hdr_frames": 3,
      "black_level": [64.0, 64.0, 64.0, 64.0],
      "white_level": 1023,
      "cct_matrix": "leica_authentic_wide",
      "noise_model": "imx858_uw_noise",
      "noise_reduction_strength": 0.50,
      "sharpness_strength": 1.10,
      "dcg_enabled": true
    },
    {
      "id": 2,
      "name": "Telephoto 3.2x (Sony IMX858 75mm)",
      "sensor": "Sony IMX858 Quad-Bayer",
      "camera_id": 2,
      "high_res": true,
      "output_resolution": "8192x6144",
      "op_mode": "0xF000",
      "raw_format": "RAW16",
      "hdr_frames": 3,
      "black_level": [64.0, 64.0, 64.0, 64.0],
      "white_level": 1023,
      "cct_matrix": "leica_authentic_tele",
      "noise_model": "imx858_tele_noise",
      "noise_reduction_strength": 0.45,
      "sharpness_strength": 1.15,
      "dcg_enabled": true
    },
    {
      "id": 3,
      "name": "Periscope Telephoto 5.0x (Sony IMX858 120mm)",
      "sensor": "Sony IMX858 Quad-Bayer",
      "camera_id": 3,
      "high_res": true,
      "output_resolution": "8192x6144",
      "op_mode": "0xF000",
      "raw_format": "RAW16",
      "hdr_frames": 3,
      "black_level": [64.0, 64.0, 64.0, 64.0],
      "white_level": 1023,
      "cct_matrix": "leica_authentic_periscope",
      "noise_model": "imx858_peri_noise",
      "noise_reduction_strength": 0.45,
      "sharpness_strength": 1.20,
      "dcg_enabled": true
    }
  ],
  "color_profile": {
    "leica_look": "authentic",
    "saturation": 1.05,
    "contrast": 1.10,
    "shadow_lift": 0.15,
    "highlight_suppression": 0.20
  }
}
